name: Go

on:
  push:
    branches: [ "setup-actions" ]
  pull_request:
    branches: [ "setup-actions" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.2

      - name: Test
        run: go test -v ./internal/cache/... ./internal/server/...
        env:
          CACHE_PATH: /cache
